// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXmGIktan_yo9psETEkEosQi7KRapvJCo',
    appId: '1:271555436914:android:d1cf0b9ade0fabebfd3deb',
    messagingSenderId: '271555436914',
    projectId: 'task-manger-44a12',
    storageBucket: 'task-manger-44a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7_m7LMtAvOLp2WsvR2sTi_97QEvpVUM',
    appId: '1:271555436914:ios:084e5a74e9a917bffd3deb',
    messagingSenderId: '271555436914',
    projectId: 'task-manger-44a12',
    storageBucket: 'task-manger-44a12.appspot.com',
    iosClientId: '271555436914-ohgs3pfg0cgr7fcoc36og99pus35gqq4.apps.googleusercontent.com',
    iosBundleId: 'com.mostafaemara.taskManger',
  );
}
